# Generated by Django 6.0.2 on 2026-03-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('specification', models.CharField(help_text='e.g. Wedding Gowns, Bespoke Suits', max_length=255)),
                ('available_status', models.BooleanField(default=True, help_text='Yes=True, No=False')),
                ('about', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tailor',
                'verbose_name_plural': 'Tailors',
                'db_table': 'tailors_tailor',
                'ordering': ['name'],
            },
        ),
    ]
